name: Insight Creative
description: "An Advertising Agency with a Vision to bring complete strategic development and creative execution capabilities into one  roll-up-your-sleeves, hard-working kind of ad agency."
url: http://insight-creative.github.io/blog
markdown: kramdown
highlighter: pygments
permalink: pretty

future: false

twitter: insightwi
