# Dependencies
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-redirect-from

# Permalinks
permalink: none

# Setup
name: Insight Creative
description: "An advertising agency with a vision to bring complete strategic development and creative execution capabilities into one roll-up-your-sleeves, hard-working kind of ad agency."
url: http://insightcreative.com
future: false

# Custom
twitter: insightwi

#Prose
prose:
  siteurl: http://insightcreative.com
  media: 'img'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
    - /css
    - /js
    - /online-ads
    - /staff-bios
    - .editorconfig
    - .gitignore
    - 404.html
    - CNAME
    - README.md
    - contact-form.html
    - feed.xml
    - /bash2014
    - /news
    - /contact
    - /services
    - /about
  metadata:
    work:
      - name: "layout"
        field:
          element: "hidden"
          value: "project"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          help: "Type the title exactly how it should appear."
          placeholder: "Your Title Goes Here"
      - name: "client"
        field:
          element: "text"
          label: "Client"
          placeholder: "Client name"
      - name: "tag"
        field:
          element: "multiselect"
          label: "Tags"
          options:
            - name: 'Case Study'
              value: 'Case Study'
            - name: 'Media Buying'
              value: 'Media Buying'
            - name: 'Web'
              value: 'Web'
            - name: 'Print'
              value: 'Print'
            - name: 'Packaging'
              value: 'Packaging'
            - name: 'Social Media'
              value: 'Social Media'
            - name: 'Identity'
              value: 'Identity'
            - name: 'Photography'
              value: 'Photography'
            - name: 'Video'
              value: 'Video'
      - name: "image"
        field:
          element: "text"
          label: "Featured Image"
          help: "Type the name of the image file you would like to feature as the display image in social media posts."
          placeholder: "image-name.jpg"
      - name: "card"
        field:
          element: "select"
          label: "Twitter Card"
          options:
            - name: 'Summary large image'
              value: 'summary large image'
            - name: 'Summary'
              value: 'summary'
            - name: 'Gallery'
              value: 'gallery'
    blog:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          help: "Type the title exactly how it should appear."
          placeholder: "Your Title Goes Here"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          options:
            - name: "Jim von Hoff"
              value: "Jim von Hoff"
            - name: "Niki Petit"
              value: "Niki Petit"
            - name: "Shelly Hendricks"
              value: "Shelly Hendricks"
            - name: "Jenny Brandenburg"
              value: "Jenny Brandenburg"
            - name: "Jay Bauer"
              value: "Jay Bauer"
            - name: "Bart Raboin"
              value: "Bart Raboin"
            - name: "Kevin McGillivray"
              value: "Kevin McGillivray"
            - name: "Zane Statz"
              value: "Zane Statz"
            - name: "Andrea Parins"
              value: "Andrea Parins"
            - name: "Stacy Allen"
              value: "Stacy Allen"
            - name: "Emily Morehart"
              value: "Emily Morehart"
            - name: "Molly Setzer"
              value: "Molly Setzer"
            - name: "Liz Van Asten"
              value: "Liz Van Asten"
            - name: "Cindy Struensee"
              value: "Cindy Struensee"
      - name: "tag"
        field:
          element: "multiselect"
          label: "Tags"
          options:
            - name: 'News'
              value: 'news'
            - name: 'Blog'
              value: 'blog'
            - name: 'Testimonial'
              value: 'testimonial'
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Featured Image"
          help: "Type the name of the image file you would like to feature as the display image in social media posts."
          placeholder: "image-name.jpg"
      - name: "card"
        field:
          element: "select"
          label: "Twitter Card"
          options:
            - name: 'Summary large image'
              value: 'summary large image'
            - name: 'Summary'
              value: 'summary'
            - name: 'Gallery'
              value: 'gallery'
