# Dependencies
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-redirect-from

# Permalinks
permalink: none

# Setup
name: Insight Creative
description: "An Advertising Agency with a Vision to bring complete strategic development and creative execution capabilities into one  roll-up-your-sleeves, hard-working kind of ad agency."
url: http://insightcreative.com
future: false

# Custom
twitter: insightwi

#Prose
prose:
  siteurl: http://insightcreative.com
  media: 'img'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
    - /css
    - /js
    - /online-ads
    - /staff-bios
    - .editorconfig
    - .gitignore
    - 404.html
    - CNAME
    - README.md
    - contact-form.html
    - feed.xml
    - /bash2014
    - /news
    - /contact
    - /services
    - /about
  metadata:
    blog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element:
          value:
      - name: "tag"
        field:
          element: "multiselect"
          label: "Tags"
          options:
            - name: 'News'
              value: 'news'
          alterable: true
        